from .server import GSIServer, GSIServerSpectator

#TODO: NOTE HERE THERES A CONSTANT
TRAINING = True


#TODO: replace MYTOKENHERE with your token
# GSI_SERVER = GSIServer(("localhost", 3000), "MYTOKENHERE")



if TRAINING:
#ONLY FOR TRAINING,
#YOU NEED A SEPARATE CSGO STEAM ACCOUNT FOR THIS
#TOKEN TO BE REPLACED HERE WILL BE THE SPECTATOR TOKEN

    #TODO: replace MYTOKENHERE with your token
    GSI_SERVER_TRAINING = GSIServerSpectator(("localhost", 3000), "Q79v5tcxVQ8u")
    GSI_SERVER_TRAINING.start_server()